### ISSUE TITLE
Mojo::DB::Results::Role and namespace

### ISSUE THREAD

**Issue by srchulo** [Grinnz/Mojo-DB-Results-Role-Struct#1]
I was wondering if you plan to release this module, and something like the `Mojo::DB::Results::Role` that you mention in the documentation:

`use Mojo::DB::ResultsRole 'apply_results_role';`

I'd get a lot of use out of this, so I'd be happy to submit pull requests/fork if you don't want to take this any further.

I also have a module that I'd like to create that I think would fall under the `Mojo::DB::ResultsRole` name space, if that would be okay with you. It's basically adding more results methods to build on the `array`, `arrays`, `hash`, and `hashes`. Two examples are:

- `kv_hash` - a key-value hash where the key is one column and the value is another.
- `hash_of_hashes `- a hash where the key is a unique column that points to the hash associated with that column.

**Comment by Grinnz** [comment]
I have released https://metacpan.org/pod/Mojo::DB::Role::ResultsRoles, as a role to be applied to Mojo::Pg or similar; and subsequently this role. Feel free to create any other general results roles in the `Mojo::DB::Results::Role::` namespace.

**Comment by srchulo** [comment]
Great, thank you!
